version: '3'


services:
    jumpbox:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: jumpbox
      ports:
        - "8443:8443"
        - "22:22"
      #network_mode: kuberneteslab
      command: sleep infinity

    server:
      build: 
        context: ./server
      container_name: server
      ports:
        - "8443:8443"
      command: sleep infinity
      #links: 
      #  - node-0
      #  - node-1

    node-0:
      build: 
        context: ./node-0
      container_name: node-0
      environment:
        - KUBELET_OPTS=--network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2.0
      networks:
        - kuberneteslab
      restart: unless-stopped

    node-1:
      build: 
        context: ./node-1
      container_name: node-1
      environment:
        - KUBELET_OPTS=--network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2.0
      networks:
        - kuberneteslab
      restart: unless-stopped



networks:
  kuberneteslab:

