version: '3'

networks:
  kuberneteslab:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"

services:
    jumpbox:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: jumpbox
      networks:
      - kuberneteslab
#      ports:
#        - "8443:8443"
#        - "22:22"
      
      command: sleep infinity

    server:
      build: 
        context: ./server
      container_name: server
      networks:
        - kuberneteslab
#      ports:
#        - "8443:8443"
      command: sleep infinity
      #links: 
      #  - node-0
      #  - node-1

    node-0:
      build: 
        context: ./node-0
      container_name: node-0
      environment:
        - KUBELET_OPTS=--network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2.0
      networks:
        - kuberneteslab
      command: sleep infinity

    node-1:
      build: 
        context: ./node-1
      container_name: node-1
      environment:
        - KUBELET_OPTS=--network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2.0
      networks:
        - kuberneteslab
      command: sleep infinity





